src/Entity/Equipe.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EquipeRepository")
 */
class Equipe
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Division")
     */
    private $division;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Division")
     */
    private $divisionPlayoff;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=40)
     */
    private $nom;

    /**
     * @var int
     *
     * @ORM\Column(name="victoires", type="integer")
     */
    private $victoires = 0;

    /**
     * @var int
     *
     * @ORM\Column(name="defaites", type="integer")
     */
    private $defaites = 0;

    /**
     * @var int
     *
     * @ORM\Column(name="victoireMap", type="integer")
     */
    private $victoireMap = 0;

    /**
     * @var int
     *
     * @ORM\Column(name="defaiteMap", type="integer")
     */
    private $defaiteMap = 0;


    /**
     * @var int
     *
     * @ORM\Column(name="nulMap", type="integer")
     */
    private $nulMap = 0;

    /**
     * @var string
     * @ORM\Column(name="capitaine", type="string")
     */
    private $capitaine;

     /**
     * @var string
     * @ORM\Column(name="discord", type="string")
     */
    private $discord;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getDivision()
    {
        return $this->division;
    }

    /**
     * @param mixed $division
     */
    public function setDivision($division)
    {
        $this->division = $division;
    }

    /**
     * @return mixed
     */
    public function getDivisionPlayoff()
    {
        return $this->divisionPlayoff;
    }

    /**
     * @param mixed $division
     */
    public function setDivisionPlayoff($division)
    {
        $this->divisionPlayoff = $division;
    }

    /**
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param string $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return int
     */
    public function getVictoires()
    {
        return $this->victoires;
    }

    /**
     * @param int $victoires
     */
    public function setVictoires($victoires)
    {
        $this->victoires = $victoires;
    }


    /**
     * @return int
     */
    public function getDefaites()
    {
        return $this->defaites;
    }

    /**
     * @param int $defaites
     */
    public function setDefaites($defaites)
    {
        $this->defaites = $defaites;
    }

    /**
     * @return int
     */
    public function getVictoireMap()
    {
        return $this->victoireMap;
    }

    /**
     * @param int $victoireMap
     */
    public function setVictoireMap($victoireMap)
    {
        $this->victoireMap = $victoireMap;
    }

    /**
     * @return int
     */
    public function getDefaiteMap()
    {
        return $this->defaiteMap;
    }

    /**
     * @param int $defaiteMap
     */
    public function setDefaiteMap($defaiteMap)
    {
        $this->defaiteMap = $defaiteMap;
    }

    /**
     * @return int
     */
    public function getNulMap()
    {
        return $this->nulMap;
    }

    /**
     * @param int $nulMap
     */
    public function setNulMap($nulMap)
    {
        $this->nulMap = $nulMap;
    }

    
    /**
     * Get the value of capitaine
     *
     * @return  string
     */ 
    public function getCapitaine()
    {
        return $this->capitaine;
    }

    /**
     * Set the value of capitaine
     *
     * @param  string  $capitaine
     *
     * @return  self
     */ 
    public function setCapitaine(string $capitaine)
    {
        $this->capitaine = $capitaine;

        return $this;
    }

    /**
     * Get the value of discord
     *
     * @return  string
     */ 
    public function getDiscord()
    {
        return $this->discord;
    }

    /**
     * Set the value of discord
     *
     * @param  string  $discord
     *
     * @return  self
     */ 
    public function setDiscord(string $discord)
    {
        $this->discord = $discord;

        return $this;
    }

    /**
     * Set the value of id
     *
     * @param  int  $id
     *
     * @return  self
     */ 
    public function setId(int $id)
    {
        $this->id = $id;

        return $this;
    }
}

src/Entity/Rencontre.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RencontreRepository")
 */
class Rencontre
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Equipe")
     */
    private $equipeDom;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Equipe")
     */
    private $equipeExt;

    /**
     * @var int
     *
     * @ORM\Column(name="num_semaine", type="integer")
     */
    private $numSemaine;

    /**
     * @ORM\Column(type="boolean")
     */
    private $jouer = false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $victoire_dom;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $score_dom;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $score_ext;

    /**
     * @ORM\Column(type="boolean")
     */
    private $playoff = false;

    

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getEquipeDom()
    {
        return $this->equipeDom;
    }

    /**
     * @param mixed $equipeDom
     */
    public function setEquipeDom($equipeDom)
    {
        $this->equipeDom = $equipeDom;
    }

    /**
     * @return mixed
     */
    public function getEquipeExt()
    {
        return $this->equipeExt;
    }

    /**
     * @param mixed $equipeExt
     */
    public function setEquipeExt($equipeExt)
    {
        $this->equipeExt = $equipeExt;
    }

    /**
     * @return int
     */
    public function getNumSemaine()
    {
        return $this->numSemaine;
    }

    /**
     * @param int $numSemaine
     */
    public function setNumSemaine($numSemaine)
    {
        $this->numSemaine = $numSemaine;
    }

    public function getJouer(): ?bool
    {
        return $this->jouer;
    }

    public function setJouer(bool $jouer): self
    {
        $this->jouer = $jouer;

        return $this;
    }

    public function getVictoireDom(): ?bool
    {
        return $this->victoire_dom;
    }

    public function setVictoireDom(?bool $victoire_dom): self
    {
        $this->victoire_dom = $victoire_dom;

        return $this;
    }

    public function getScoreDom(): ?int
    {
        return $this->score_dom;
    }

    public function setScoreDom(?int $score_dom): self
    {
        $this->score_dom = $score_dom;

        return $this;
    }

    public function getScoreExt(): ?int
    {
        return $this->score_ext;
    }

    public function setScoreExt(int $score_ext): self
    {
        $this->score_ext = $score_ext;

        return $this;
    }

    public function getPlayoff(): ?bool
    {
        return $this->playoff;
    }

    public function setPlayoff(bool $playoff): self
    {
        $this->playoff = $playoff;

        return $this;
    }
}

src/Controller/Front/DefaultController.php
<?php

namespace App\Controller\Front;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Championnat;
use App\Entity\GagnantSaison;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $numSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getSemaine();
        return $this->render('front/default/index.html.twig', [
            "numSemaine" => $numSemaine
        ]);
    }

    /**
    * @Route("/terms", name="terms")
    */
    public function terms(){
        $em = $this->getDoctrine()->getManager();
        $numSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getSemaine();
        return $this->render('front/default/terms.html.twig', [
            "numSemaine" => $numSemaine
        ]);
    }

    /**
    * @Route("/twitch", name="twitch")
    */
    public function twitch(){
        $em = $this->getDoctrine()->getManager();
        $numSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getSemaine();
        return $this->render('front/default/twitch.html.twig', [
            "numSemaine" => $numSemaine
        ]);
    }

    /**
    * @Route("/winner", name="play_win")
    */
    public function playoffsWinner(){
        $em = $this->getDoctrine()->getManager();
        $numSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getSemaine();
        $winners = $em->getRepository(GagnantSaison::class)->findAll();
        return $this->render('front/default/winners_playoffs.html.twig', [
            "numSemaine" => $numSemaine,
            "winners" => array_reverse($winners)
        ]);
    }
}

src/Controller/Front/EquipeController.php
<?php

namespace App\Controller\Front;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Validator\Constraints\DateTime;
use App\Entity\Equipe;
use App\Entity\Division;
use App\Entity\Rencontre;
use App\Entity\Map;
use App\Entity\MapPool;
use App\Entity\Championnat;

class EquipeController extends AbstractController
{

    const PASSWORD = "TScreateM4tchs";

    /**
     * @Route("/teams", name="show_team")
     */
    public function showTeams()
    {
        $em = $this->getDoctrine()->getManager();
        $equipes = $em->getRepository(Equipe::class)->findAll();
        $divisions = $em->getRepository(Division::class)->findDivAvecEquipe();
        $rencontres = $em->getRepository(Rencontre::class)->findAll();
        $numSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getSemaine();
        return $this->render('front/equipe/show_teams.html.twig', [
            'equipes'=>$equipes,
            'divisions'=>$divisions,
            'rencontres'=>$rencontres,
            "numSemaine" => $numSemaine
        ]);
    }

    /**
    * @Route("/standing", name="standing")
    */
    public function standing(){
        $em = $this->getDoctrine()->getManager();
        $equipes = $em->getRepository(Equipe::class)->findAll();
        $divisions = $em->getRepository(Division::class)->findAll();
        $numSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getSemaine();

        usort($equipes, function($a, $b) {
            if ($a->getVictoires() == $b->getVictoires())
            {
              // score is the same, sort by endgame
              if (($a->getVictoireMap() - $a->getDefaiteMap()) < ($b->getVictoireMap() - $b->getDefaiteMap())) return 1;
            }
            // sort the higher score first:
            return $a->getVictoires() < $b->getVictoires() ? 1 : -1;
        });
        return $this->render('front/equipe/show_standing.html.twig', [
            'equipes'=>$equipes,
            'divisions'=>$divisions,
            "numSemaine" => $numSemaine
        ]);
    }

    /**
    * @Route("/meetings", name="show_renc")
    */
    public function match(){
        $em = $this->getDoctrine()->getManager();
        $rencontres = $em->getRepository(Rencontre::class)->findAll();
        $divisions = $em->getRepository(Division::class)->findDivAvecEquipe();
        $numSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getSemaine();
        $nbSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getNbSemaine();
        $datesSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getDatesSemaines();
        $datesNextSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getDatesNextSemaines();
        $HeroBanS1 = $em->getRepository(Championnat::class)->findAll()[0]->getHeroBanS1();
        $HeroBanS2 = $em->getRepository(Championnat::class)->findAll()[0]->getHeroBanS2();
        $mapPools = $em->getRepository(MapPool::class)->findAll();
        return $this->render('front/equipe/show_matchs.html.twig', [
            'rencontres'=>$rencontres,
            'divisions'=>$divisions,
            'mapPools'=>$mapPools,
            'numSemaine'=>$numSemaine,
            'nbSemaine'=>$nbSemaine,
            'datesSemaine'=>$datesSemaine,
            'datesNextSemaine'=>$datesNextSemaine,
            'heroBanS1' => $HeroBanS1,
            'heroBanS2' => $HeroBanS2,
        ]);
    }

    /**
    * @Route("/meetings/playoff", name="show_renc_playoff")
    */
    public function playoff(){
        $em = $this->getDoctrine()->getManager();
        $divisions = $em->getRepository(Division::class)->findDivAvecEquipePlayoff();
        $datesSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getDatesSemaines();
        $datesNextSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getDatesNextSemaines();
        $numSemaine = $em->getRepository(Championnat::class)->findAll()[0]->getSemaine();
        $mapPools = $em->getRepository(MapPool::class)->findAll();
        $rencontres = $em->getRepository(Rencontre::class)->findAll();

        return $this->render('front/equipe/show_matchs_playoff.html.twig',[
            "divisions" => $divisions,
            "numSemaine" => $numSemaine,
            'datesSemaine'=>$datesSemaine,
            'mapPools'=>$mapPools,
            'rencontres'=>$rencontres,
            'numNextSemaine'=> $numSemaine + 1,
            'datesNextSemaine'=>$datesNextSemaine
        ]);
    }


    //Génération aléatoire des rencontres
    function scheduler($teams, $division){
        if (count($teams)%2 != 0){
            $teamBye = new Equipe();
            $teamBye->setNom("BYE");
            $teamBye->setId(0);
            array_push($teams,$teamBye);
        }
        $away = array_splice($teams,(count($teams)/2));
        $home = $teams;
        for ($i=0; $i < count($home)+count($away)-1; $i++){
            for ($j=0; $j<count($home); $j++){
                $round[$i][$j]["Home"]=$home[$j];
                $round[$i][$j]["Away"]=$away[$j];
            }
            if(count($home)+count($away)-1 > 2){
                $temp2 = array_splice($home,1,1);
                $temp = array_shift($temp2);
                array_unshift($away,$temp);
                array_push($home,array_pop($away));
            }
        }
        return $round;
    }

     /**
     * @Route("/rencontre/create", name="create_renc")
     */
    public function creationRencontres(Request $request)
    {
        if($request->isMethod('POST')){
            if($request->request->has('formCreate')) {
                $password = $request->request->get('password');

                if ($password === self::PASSWORD) {
                    $em = $this->getDoctrine()->getManager();
                    $divisions = $em->getRepository(Division::class)->findDivAvecEquipe();
                    foreach ($divisions as $division) {
                        $equipes = $em->getRepository(Equipe::class)->findByDiv($division);
                        $schedule = $this->scheduler($equipes, $division);
                        foreach ($schedule AS $round => $games) {
                            foreach ($games AS $play) {
                                $rencontre = new Rencontre();
                                $rencontre->setNumSemaine($round + 1);
                                $rencontre->setEquipeDom($play["Home"]);
                                $rencontre->setEquipeExt($play["Away"]);
                                if($rencontre->getEquipeDom()->getId() != 0 && $rencontre->getEquipeExt()->getId() != 0) {
                                    $em->persist($rencontre);
                                }
                            }
                        }
                    }
                    $em->flush();
                    $request->getSession()->getFlashBag()->add('success', "Les rencontres ont été crééééees");
                    return $this->redirectToRoute('index');

                } else {
                    return $this->render('BackBundle:Rencontre:administration.html.twig', array(
                        'message' => "Wrong password"
                    ));
                }
            }
        }
        return $this->render('front/equipe/administration.html.twig');
    }


}

templates/front/equipe/administration.html.twig
{% extends 'front/base.html.twig' %}
{% block title %} - Administration des rencontres{% endblock %}
{% block body %}
    <p>{% if message is defined %}<span>{{ message }}</span>{% endif %}</p>
    <form name="formCreate" method="post" action="{{ path('create_renc') }}">
        <input type="hidden" name="formCreate" value="on"/>
        <div>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password"
                   required
                   placeholder="Mot de passe" />
        </div>
        <input type="submit" />
    </form>

{% endblock %}

templates/front/equipe/show_standing.html.twig
{% extends 'front/base.html.twig' %}


{% block disabled_matchs %}
    {% if numSemaine > 6 %}
        isDisabled
    {% endif %}
{% endblock %}

{% block disabled_matchs_small %}
    {% if numSemaine > 6 %}
        isDisabled
    {% endif %}
{% endblock %}

{% block title %} - Classements{% endblock %}

{% block css %}
    <style>
        .tabs-correct {
            overflow-x: hidden !important;
        }
    </style>
{% endblock %}

{% block body %}
{% set position = 0 %}

    <div class="main-content">
        <h2 class="center-align">Classements</h2>

        <div class="spacer-1"></div>


        <div class="row">
            <div class="col s12">
                <ul class="tabs tabs-fixed-width tabs-correct">
                    {% for division in divisions %}
                        {% if division.playoff == false %}
                            <li class="tab col s2"><a href="#{{ division.id }}">{{ division.nom }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
            {% for division in divisions %}
                {% if division.playoff == false %}
                <div id="{{ division.id }}" class="col s12">
                    <table class="striped">
                        <thead>
                        <tr>
                            <th><p class="">Rang</p></th>
                            <th><p class="">Equipe</p></th>
                            <th>V</th>
                            <th>D</th>
                            <th>J</th>
                            <th>Cartes G-P-N</th>
                            <th>Diff</th>
                        </tr>
                        </thead>

                        <tbody>

                        {% set diffEquipePrec = "" %}
                        {% set winEquipePrec = "" %}
                        {% for equipe in equipes %}
                            {% if equipe.division.id == division.id %}
                                {% set nbMatchs = equipe.victoires + equipe.defaites %}
                                {% set diffEquipe = equipe.victoireMap - equipe.defaiteMap %}
                                {% set position = position + 1 %}
                                {% set winEquipe = equipe.victoires %}
                                {% if diffEquipe == diffEquipePrec and winEquipePrec !="" and winEquipe == winEquipePrec %}
                                    {% set position = position - 1 %}
                                {% endif %}
                                <tr>
                                    <td><p class="">{{ position }}</p></td>
                                    <td>
                                        {{ equipe.nom }}
                                    </td>
                                    <td>{{ equipe.victoires }}</td>
                                    <td>{{ equipe.defaites }}</td>
                                    <td>{{ nbMatchs }}</td>
                                    <td>{{ equipe.victoireMap }} - {{ equipe.defaiteMap }} - {{ equipe.nulMap }}</td>
                                    <td>{% if diffEquipe >= 0 %}+{% endif %}{{ diffEquipe }}</td>
                                </tr>
                                {% set diffEquipePrec = diffEquipe %}
                                {% set winEquipePrec = winEquipe %}
                            {% endif %}
                        {% endfor %}
                        {% set position = 0 %}
                        {% set diffEquipePrec = "" %}
                        {% set winEquipePrec = "" %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <div class="spacer-2"></div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function(){
            $('ul.tabs').tabs();
        });
    </script>
{% endblock %}

templates/front/equipe/show_teams.html.twig
{% extends 'front/base.html.twig' %}


{% block disabled_matchs %}
    {% if numSemaine > 6 %}
        isDisabled
    {% endif %}
{% endblock %}

{% block disabled_matchs_small %}
    {% if numSemaine > 6 %}
        isDisabled
    {% endif %}
{% endblock %}

{% block title %} - Les équipes{% endblock %}

{% block css %}
<style>
    .flex-history{
        display: flex;
    }

    .flex-history *{
        margin: 10px;
    }

    .pointer{
        cursor: pointer;
    }
</style>
{% endblock %}

{% block body %}
<div class="main-content">

    <h2 class="center-align">Les équipes</h2>

    <div class="spacer-1"></div>

    <div class="container hide-on-med-and-down">
        <div style="display: flex; flex-wrap: wrap; justify-content: center">
            {% for division in divisions %}
            <div style="width: 40%; margin: 20px;" id="{{division.id}}">
                <ul class="collection with-header">
                    <li class="collection-header avatar">
                        <img src={{ asset('img/ranks/' ~division.code~ '.png') }} alt="" width="40px">
                        <h4 style="display:inline-block">{{division.nom}}</h4>
                    </li>
                    {% for equipe in equipes %}
                    {% if equipe.division.id == division.id %}
                    <li class="collection-item">
                        <span>{{equipe.nom}}</span>
                        <a id="{{ equipe.id }}-click" class="pointer"><span class="new badge" data-badge-caption="Historique"></span></a>
                    </li>
                    <div id="{{ equipe.id }}-history">
                        {% for rencontre in rencontres %}
                            {% if rencontre.jouer %}
                                {% if rencontre.equipeDom.id == equipe.id %}
                                    <div class="flex-history"><img src="{{ asset('img/vs.png') }}" width="20px"> <span>{{ rencontre.equipeExt.nom }} - {% if rencontre.victoireDom %} Victoire {% else %} Défaite {% endif %} {{ rencontre.scoreDom }}-{{ rencontre.scoreExt }} </span> </div>
                                {% endif %}
                                {% if rencontre.equipeExt.id == equipe.id %}
                                    <div class="flex-history">
                                        <img src="{{ asset('img/vs.png') }}" width="20px"> <span> {{ rencontre.equipeDom.nom }}  - {% if rencontre.victoireDom %} Défaite {% else %} Victoire {% endif %} {{ rencontre.scoreExt }}-{{ rencontre.scoreDom }}</span>
                                    </div>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
            {% endfor %}
        </div>
    </div>


    <div class="container hide-on-large-only">
        <div style="display: flex; flex-wrap: wrap; justify-content: center">
            {% for division in divisions %}
            <div style="width: 100%; margin: 20px;" id="{{division.id}}">
                <ul class="collection with-header">
                    <li class="collection-header avatar">
                        <img src={{asset('/img/rank/'~division.code~'.png')}} alt="" width="40px">
                        <h4 style="display:inline-block">{{division.nom}}</h4>
                    </li>
                    {% for equipe in equipes %}
                    {% if equipe.division.id == division.id %}
                    <li class="collection-item">
                        <span>{{equipe.nom}}</span>
                        <a id="{{ equipe.id }}-click-small" class="pointer"><span class="new badge" data-badge-caption="Historique"></span></a>
                    </li>
                    <div id="{{ equipe.id }}-history-small">
                        {% for rencontre in rencontres %}
                            {% if rencontre.jouer %}
                                {% if rencontre.equipeDom.id == equipe.id %}
                                    <div class="flex-history"><img src="{{ asset('img/vs.png') }}" width="20px"> <span>{{ rencontre.equipeExt.nom }} - {% if rencontre.victoireDom %} Victoire {% else %} Défaite {% endif %} {{ rencontre.scoreDom }}-{{ rencontre.scoreExt }} </span> </div>
                                {% endif %}
                                {% if rencontre.equipeExt.id == equipe.id %}
                                    <div class="flex-history">
                                        <img src="{{ asset('img/vs.png') }}" width="20px"> <span> {{ rencontre.equipeDom.nom }}  - {% if rencontre.victoireDom %} Défaite {% else %} Victoire {% endif %} {{ rencontre.scoreExt }}-{{ rencontre.scoreDom }}</span>
                                    </div>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    $(document).ready(function() {
        {% for equipe in equipes %}
            $("#" + {{ equipe.id }} + "-history").hide();
             $("#" + {{ equipe.id }} + "-history-small").hide();

            if($("#" + {{ equipe.id }} + "-history").children().length > 0){
                $("#" + {{ equipe.id }} + "-history").append('<hr width="100%" color="#e0e0e0"> ');
            }

            if($("#" + {{ equipe.id }} + "-history-small").children().length > 0){
                $("#" + {{ equipe.id }} + "-history-small").append('<hr width="100%" color="#e0e0e0"> ');
            }

            $("#" + {{ equipe.id }} + "-click").click(function(){
                if($("#" + {{ equipe.id }} + "-history").is(":visible")){
                    $("#" + {{ equipe.id }} + "-history").slideUp();
                }
                else{
                    $("#" + {{ equipe.id }} + "-history").slideDown();
                }

                {% for e in equipes %}
                    {% if e.id != equipe.id %}
                        if($("#" + {{ e.id }} + "-history").is(":visible")){
                            $("#" + {{ e.id }} + "-history").slideUp();
                        }
                    {% endif %}
                {% endfor %}

            });

            $("#" + {{ equipe.id }} + "-click-small").click(function(){
                if($("#" + {{ equipe.id }} + "-history-small").is(":visible")){
                    $("#" + {{ equipe.id }} + "-history-small").slideUp();
                }
                else{
                    $("#" + {{ equipe.id }} + "-history-small").slideDown();
                }

                {% for e in equipes %}
                    {% if e.id != equipe.id %}
                        if($("#" + {{ e.id }} + "-history-small").is(":visible")){
                            $("#" + {{ e.id }} + "-history-small").slideUp();
                        }
                    {% endif %}
                {% endfor %}
            });
        {% endfor %}
    });
</script>
{% endblock %}